#!/bin/sh
#
# An example hook script to check the commit log message.
# Called by "git commit" with one argument, the name of the file
# that has the commit message.  The hook should exit with non-zero
# status after issuing an appropriate message if it wants to stop the
# commit.  The hook is allowed to edit the commit message file.
#
# To enable this hook, rename this file to "commit-msg".

# Uncomment the below to add a Signed-off-by line to the message.
# Doing this in a hook is a bad idea in general, but the prepare-commit-msg
# hook is more suited to it.
#
if ! echo "$COMMIT_MSG" | grep -qE "^(feat|fix|hotfix|imp):"; then
    echo "Erreur : Le message de commit doit commencer par un des mots-clés suivants :"
    echo "  feat, fix, hotfix, imp"
    exit 1
fi

# Si tout est correct, continuer
exit 0
