#!/bin/sh
#
# An example hook script to verify what is about to be committed.
# Called by "git commit" with no arguments.  The hook should
# exit with non-zero status after issuing an appropriate message if
# it wants to stop the commit.
#
# To enable this hook, rename this file to "pre-commit".

FILES=$(git diff --cached --name-only --diff-filter=ACM | grep '\.js$')
if [ -n "$FILES" ]; then
    echo "Exécution de ESLint..."
    eslint $FILES
    if [ $? -ne 0 ]; then
        echo "Linting échoué. Corrigez les erreurs avant de committer."
        exit 1
    fi
fi

echo "Linting réussi. Commit autorisé."
exit 0

