name: Protect main branch

on:
  pull_request:
    branches:
      - main
    types: [opened, reopened]
jobs:
  check-branch:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Log branch info
        run: |
          echo "Head branch: ${{ github.event.pull_request.head.ref }}"
          echo "Base branch: ${{ github.event.pull_request.base.ref }}"
      - name: Check branch
        run: |
          if [[ ${{ github.event.pull_request.head.ref }} == "dev" && ${{ github.event.pull_request.base.ref }} == "main" ]]; then
            echo "This PR is from the dev branch to the main branch"
            exit 0
          else
            echo "This PR is not from the dev branch to the main branch"
            exit 1
          fi
